name: Manual Flutter Build

on:
  workflow_dispatch:
    inputs:
      build_target:
        description: 'Select Build Type'
        required: true
        default: 'apk-release'
        type: choice
        options:
          - apk-debug
          - apk-release
          - aab-release

jobs:
  build:
    name: Build Flutter App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0' # Sesuaikan dengan versi Flutter yang ingin digunakan
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK Debug
        if: ${{ github.event.inputs.build_target == 'apk-debug' }}
        run: flutter build apk --debug

      - name: Build APK Release
        if: ${{ github.event.inputs.build_target == 'apk-release' }}
        run: flutter build apk --release

      - name: Build AAB Release
        if: ${{ github.event.inputs.build_target == 'aab-release' }}
        run: flutter build appbundle

      - name: Upload APK Debug
        if: ${{ github.event.inputs.build_target == 'apk-debug' }}
        uses: actions/upload-artifact@v3
        with:
          name: aniriot-apk-debug
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Upload APK Release
        if: ${{ github.event.inputs.build_target == 'apk-release' }}
        uses: actions/upload-artifact@v3
        with:
          name: aniriot-apk-release
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload AAB Release
        if: ${{ github.event.inputs.build_target == 'aab-release' }}
        uses: actions/upload-artifact@v3
        with:
          name: aniriot-aab-release
          path: build/app/outputs/bundle/release/app-release.aab
